#!/bin/bash

#MANDATORY FOR LAUNCHER

SLURM_CPUS_PER_TASK=36

SBATCH_TIMELIMIT=48:00:00

SCRIPT=apptainer

#MANDATORY FOR APPTAINER

PATH_TO_HOST_WORKING_DIRECTORY=$project_folder

IMAGE=images/motus

SCRIPT_APPTAINER=submitters/bash_motus

#SBATCH THE JOB

sbatch --cpus-per-task $SLURM_CPUS_PER_TASK --time $SBATCH_TIMELIMIT \
launcher.sh $SCRIPT \
$PATH_TO_HOST_WORKING_DIRECTORY $IMAGE $SCRIPT_APPTAINER
